application: comp3001-1213-b
version: 0000000
runtime: python27
api_version: 1
threadsafe: false
libraries:
- name: django
  version: "1.4"
handlers:
- url: /images
  static_dir: web/static/images
- url: /.*
  script: django_handler.py
