application: comp3001-1213-b
version: 0000000
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: django
  version: "1.3"
handlers:
- url: /images
  static_dir: web/static/images
- url: /css
  static_dir: web/static/css
- url: /.*
  script: django_handler.app
